version: "3.8"
services:
  tomcat:
    image: tomcat:9.0
    volumes:
      - ./target/Helper-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/helper.war
    ports:
      - "8088:8080"
    restart: on-failure